### ISSUE TITLE
Plugin can't activate

### ISSUE THREAD

**Issue by proyectomovin** [ViralAgency/Dolipress#2]
Error when i actived the plugin on wordpress 6.1:

"Fatal error: Uncaught Error: Class 'GFAPI' not found in /home/patago27/public_html/wp-content/plugins/Dolipress-main/functions.php:209 Stack trace: #0 /home/patago27/public_html/wp-content/plugins/Dolipress-main/functions.php(24): dpfg_get_form_id() #1 /home/patago27/public_html/wp-content/plugins/Dolipress-main/index.php(30): dolipress_init() #2 /home/patago27/public_html/wp-admin/includes/plugin.php(2314): include_once('/home/patago27/...') #3 /home/patago27/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape('Dolipress-main/...') #4 {main} thrown in /home/patago27/public_html/wp-content/plugins/Dolipress-main/functions.php on line 209"

**Comment by ViralAgency** [comment]
Thanks for the report, @proyectomovin. I'm having the same problem, which will likely require a component update. I'll get right to work fixing it.

**Comment by ViralAgency** [comment]
Thanks for the report,  @proyectomovin . I'm having the same problem, which will likely require a component update. I'll get right to work fixing it.
